summary: Create a new task
tags:
  - Tasks
security:
  - bearerAuth: []
requestBody:
  required: true
  content:
    application/json:
      schema:
        type: object
        required: [title, status, project_id]
        properties:
          title:
            type: string
            maxLength: 255
          description:
            type: string
            nullable: true
          status:
            type: string
            enum: [pending, completed]
          project_id:
            type: integer
responses:
  '201':
    description: Task created
    content:
      application/json:
        schema:
          $ref: '../../components/schemas/Task.yaml'
  '401':
    $ref: '../../components/responses/ErrorResponses.yaml#/UnauthorizedError'
  '422':
    $ref: '../../components/responses/ErrorResponses.yaml#/ValidationError'
  '500':
    $ref: '../../components/responses/ErrorResponses.yaml#/ServerError'
