summary: List all tasks
tags:
  - Tasks
security:
  - bearerAuth: []
responses:
  '200':
    description: Successful operation
    content:
      application/json:
        schema:
          type: array
          items:
            $ref: '../../components/schemas/Task.yaml'
  '401':
    $ref: '../../components/responses/ErrorResponses.yaml#/UnauthorizedError'
  '500':
    $ref: '../../components/responses/ErrorResponses.yaml#/ServerError'
